# Field Lights for Kitty
foreground #D9D7CE
background #1A1F28
selection_foreground none
selection_background #343F4C
url_color #FFAE57
cursor #FFCC66
cursor_text_color background

# Normal colors
color0  #343D4A
color1  #F07178
color2  #BAE67E
color3  #FFCC66
color4  #36A3D9
color5  #D4BFFF
color6  #95E6CB
color7  #C7C7C7

# Bright colors
color8  #686868
color9  #F07178
color10 #CBE645
color11 #FFDF80
color12 #6871FF
color13 #FF77FF
color14 #A6FDE1
color15 #FFFFFF

# Tab bar colors
active_tab_foreground #FFCC66
active_tab_background #212733
inactive_tab_foreground #738699
inactive_tab_background #1A1F28
tab_bar_background #1A1F28

