# ~/.config/starship.toml

[cmd_duration]
min_time = 10_000                    # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[character]
success_symbol = "▲(bold green)"
error_symbol = "[✖](bold red)"
