# Add deno completions to search path
if [[ ":$FPATH:" != *":/Users/mike/.zsh/completions:"* ]]; then export FPATH="/Users/mike/.zsh/completions:$FPATH"; fi
# start starship
eval "$(starship init zsh)"

ZSH_DISABLE_COMPFIX=true

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Export my language settings.
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Define the theme.
# ZSH_THEME="chronos"
ZSH_THEME=""

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=5

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Change the tab_title to a fixed string.
# Make sure that AUTO_TITLE is disabled.
function precmd () {
	print -Pn - '\e]0;%~\a'
	# title="`hostname`"
	# window_title="print -P - '\e]0;$title\a'"
	# echo -ne "$window_title"
}

# Waiting dots.
COMPLETION_WAITING_DOTS="true"

# History file and size settings.
HISTFILE=~/.histfile
HISTSIZE=20000
SAVEHIST=10000

# Disable bell ring notification thingy.
setopt notify
bindkey -e

# Load Plugin
plugins=(
	git
)

# Don't delete this.
source $ZSH/oh-my-zsh.sh

### User configuration ###

# Load aliases and fzf.
[ -f "$HOME/.config/aliasrc" ] && source "$HOME/.config/aliasrc"

# ZSH_AUTOSUGGEST change the color
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#5fafd7,bold"
ZSH_AUTOSUGGEST_USE_ASYN=true

export PATH
export EDITOR=nvim

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

autoload -U add-zsh-hook
load-nvmrc() {
  local node_version="$(nvm version)"
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" = "N/A" ]; then
      nvm install
    elif [ "$nvmrc_node_version" != "$node_version" ]; then
      nvm use
    fi
  elif [ "$node_version" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}

add-zsh-hook chpwd load-nvmrc

# ctrl+k = accept suggestions
bindkey '^k' autosuggest-accept
# ctrl+l = forward-word in suggestions
bindkey '^l' forward-word 
# ctrl+l = backward-word in suggestions
bindkey '^h' backward-word 

# pnpm
export PNPM_HOME="/Users/mike/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

# pnpm end

# export java
export PATH="/opt/homebrew/opt/openjdk@17/bin:$PATH"

# export sdkmanager and other android cmd tools
export PATH="/opt/homebrew/share/android-commandlinetools/cmdline-tools/latest/bin:$PATH"


# export python installed with brew
export PATH="$(brew --prefix python)/libexec/bin:$PATH"

export PATH="/Users/mike/.local/bin:$PATH"

source $HOMEBREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh


# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/mike/.lmstudio/bin"
export PATH="/Users/mike/.config/herd-lite/bin:$PATH"
export PHP_INI_SCAN_DIR="/Users/mike/.config/herd-lite/bin:$PHP_INI_SCAN_DIR"
eval 
TWILIO_AC_BASH_SETUP_PATH=/Users/mike/.twilio-cli/autocomplete/bash_setup && test -f $TWILIO_AC_BASH_SETUP_PATH && source $TWILIO_AC_BASH_SETUP_PATH; # twilio autocomplete setup

# twilio main account credentials
. "/Users/mike/.deno/env"

# Initialize zsh completions (added by deno install script)
autoload -Uz compinit && compinit -u
compinit
# bun completions
[ -s "/Users/mike/.bun/_bun" ] && source "/Users/mike/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

