# start starship
eval "$(starship init zsh)"

ZSH_DISABLE_COMPFIX=true

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Export my language settings.
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Define the theme.
# ZSH_THEME="chronos"
ZSH_THEME=""

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=5

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Change the tab_title to a fixed string.
# Make sure that AUTO_TITLE is disabled.
function precmd () {
	print -Pn - '\e]0;%~\a'
	# title="`hostname`"
	# window_title="print -P - '\e]0;$title\a'"
	# echo -ne "$window_title"
}

# Waiting dots.
COMPLETION_WAITING_DOTS="true"

# History file and size settings.
HISTFILE=~/.histfile
HISTSIZE=20000
SAVEHIST=10000

# Disable bell ring notification thingy.
setopt notify
bindkey -e

# Load Plugin
plugins=(
	git
	zsh-autosuggestions
	zsh-syntax-highlighting
	zsh-npm-scripts-autocomplete
    fzf-zsh-plugin
)

# Don't delete this.
source $ZSH/oh-my-zsh.sh

### User configuration ###

# Load aliases and fzf.
[ -f "$HOME/.config/aliasrc" ] && source "$HOME/.config/aliasrc"

# fzf config
export FZF_PREVIEW_ADVANCED=true
export FZF_DEFAULT_COMMAND='rg --files --hidden --glob "!.git"'
export FZF_DEFAULT_OPTS='-i --height=50%'

# ZSH_AUTOSUGGEST change the color
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#5fafd7,bold"
ZSH_AUTOSUGGEST_USE_ASYN=true
# change the keybinding for 'accepting' the suggestion to 2x TAB
bindkey '^ ' autosuggest-accept

# append golang to the $PATH
path+=("$HOME/go/bin")
path+=('/usr/local/go/bin')
export PATH
export EDITOR=nvim
# set the terminal
# export TERM="xterm-256color"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
. "$HOME/.cargo/env"

export OPENSSL_CONF=/dev/null

export MANPATH=$HOME/tools/ripgrep/doc/man:$MANPATH
export FPATH=$HOME/tools/ripgrep/complete:$FPATH

# set max node mem usage to 8GB
NODE_OPTIONS="--max-old-space-size=8192"

# export java
export JAVA_HOME=/usr/lib/jvm/java-22-openjdk-amd64
export JDK_HOME=$JAVA_HOME/bin

# export maven
export M2_HOME=/opt/maven

# export android build struff
export ANDROID_SDK_ROOT=$HOME/Android/Sdk
export ANDROID_HOME=$ANDROID_SDK_ROOT
export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools/
export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/
export PATH=$PATH:$ANDROID_SDK_ROOT/emulator/
export PATH=$PATH:$JAVA_HOME/bin/
export PATH=$PATH:$JDK_HOME
export PATH=$PATH:$M2_HOME/bin/

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# pnpm
export PNPM_HOME="$HOME/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# Turso
export PATH="$HOME/.turso:$PATH"
