# vim:fileencoding=utf-8:ft=conf
#
# import theme
include themes/kitty-themes/themes/everforest_dark_medium.conf
# include themes/kitty-themes/themes/Doom_One_Light.conf

# font and ligatures
font_size 12
font_family GeistMono Nerd Font
bold_font GeistMono Nerd Font Bold
italic_font GeistMono Nerd Font Italic
disable_ligatures never

# cursor
cursor_shape block
cursor_blink_interval -1

# window (floating) sizes
remember_window_size no
initial_window_width 100c
initial_window_height 34c
# set padding in terminal
window_padding_width 6

# map copy and paste behaviour
strip_trailing_spaces always
copy_on_select yes
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# disblae titlebar
hide_window_decorations yes

# disable stupid audio
enable_audio_bell false
