# vim:fileencoding=utf-8:ft=conf
#
# import theme
# include themes/kitty-themes/themes/everforest_dark_medium.conf
#include themes/deepwhite.conf
include themes/field_lights.conf

# font and ligatures
font_size 12
font_family Geist Nerd Font
bold_font Geist Nerd Font Bold
italic_font Geist Nerd Font Italic
disable_ligatures never

# cursor
cursor_shape block
cursor_blink_interval -1

# window (floating) sizes
remember_window_size yes
initial_window_width 100c
initial_window_height 34c
# set padding in terminal
window_padding_width 2

# map copy and paste behaviour
strip_trailing_spaces always
copy_on_select yes
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# disblae titlebar
hide_window_decorations no

# disable stupid audio
enable_audio_bell false
