# global options
set -g default-terminal "xterm-256color"
set -g escape-time 40
set -g allow-rename off
set -g mouse on

## Window options
set -g base-index 1

## Pane options
setw -g pane-base-index 1
setw -g visual-bell off
setw -g visual-activity on

# true color settings
#set -g default-terminal "$TERM"
#set -ag terminal-overrides ",$TERM:Tc"

# Prefix binds
## General binds
bind g send-keys C-g
bind : command-prompt



set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M
bind -n C-WheelUpPane select-pane -t= \; copy-mode -e \; send-keys -M
bind -T copy-mode-vi    C-WheelUpPane   send-keys -X halfpage-up
bind -T copy-mode-vi    C-WheelDownPane send-keys -X halfpage-down
bind -T copy-mode-emacs C-WheelUpPane   send-keys -X halfpage-up
bind -T copy-mode-emacs C-WheelDownPane send-keys -X halfpage-down

# To copy, left click and drag to highlight text in yellow, 
# once you release left click yellow text will disappear and will automatically be available in clibboard
# # Use vim keybindings in copy mode
setw -g mode-keys vi
# Update default binding of `Enter` to also use copy-pipe
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -selection c"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"


# hop between panels (vim keybindings)
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# split windows (sane keybindings)
bind -r v run-shell 'tmux split-window -v -c "#{pane_current_path}"'
bind -r m run-shell 'tmux split-window -hf -c "#{pane_current_path}"'
bind -r o run-shell 'tmux split-window -p 33 -c "#{pane_current_path}"'

# themeing
set -g status-position top
set -g status-justify left
set -g status-style 'fg=#fabd2f'

set -g status-left ''
set -g status-right '#{pane_current_path} '
set -g status-right-length 80
set -g status-left-length 10

setw -g window-status-current-style 'fg=#504945 bg=#fabd2f bold'
setw -g window-status-current-format ' #I | #W '

setw -g window-status-style 'fg=#bdae93 dim'
setw -g window-status-format ' #I | #W '
setw -g window-status-bell-style 'fg=#3c3836 bg=#fb4934 bold'

# reload the config on the fly
bind-key r source-file $HOME/.config/tmux/tmux.conf \; display-message "$HOME/.config/tmux/tmux.conf reloaded"
